# Generated by Django 6.1.1 on 2026-09-14 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('predicted_crop', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('alternatives', models.JSONField(default=list)),
                ('model_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=32)),
                ('symptoms_selected', models.JSONField()),
                ('results', models.JSONField(help_text='Ranked list of {rule_id, conclusion, cf, advice}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLModelMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('accuracy', models.FloatField()),
                ('n_training_samples', models.PositiveIntegerField()),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('maize', 'Maize'), ('tomato', 'Tomato'), ('beans', 'Beans'), ('cabbage', 'Cabbage'), ('potato', 'Potato'), ('general', 'General / Any crop')], default='general', max_length=32)),
                ('conclusion', models.CharField(help_text="e.g. 'Fall Armyworm infestation'", max_length=120)),
                ('symptoms', models.JSONField(help_text='List of symptom codes this rule looks for')),
                ('base_cf', models.FloatField(default=0.6, help_text='Certainty factor, 0..1')),
                ('advice', models.TextField(help_text='Recommended action shown to the farmer')),
                ('times_confirmed', models.PositiveIntegerField(default=0)),
                ('times_rejected', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=200)),
                ('crop', models.CharField(default='general', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CropFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_best_crop', models.CharField(max_length=64)),
                ('was_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.croprecommendationsession')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.diagnosissession')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rule')),
            ],
        ),
    ]
